sudo: required
services:
  - docker

before_install:
  - docker build -t sachinim/docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sachinim/docker-test npm test

after_success:
  - docker build -t sachinim/docker-test-client ./client
  - docker build -t sachinim/docker-test-nginx ./nginx
  - docker build -t sachinim/docker-test-server ./server
  - docker build -t sachinim/docker-test-worker ./worker

  # Push images to docker hub
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sachinim/docker-test-client
  - docker push sachinim/docker-test-nginx
  - docker push sachinim/docker-test-server
  - docker push sachinim/docker-test-worker

# deploy: